### ISSUE TITLE
Deprecated request package

### ISSUE THREAD

**Issue by j-koziel** [cm-core-team/wol-api#11]
The request package we are using seems to be [heavily deprecated](https://github.com/request/request/issues/3142) and I was wondering if we could implement an alternative.

I have found one which I haven't yet tested.
It's called [got](https://www.npmjs.com/package/got)

Let me know what you think.
I think however that although it is deprecated it seems to be fast and if there is not suitable alternative which is just as fast or even faster we should just stick with request for now.

**Comment by j-koziel** [comment]
I can compile a list of alternatives to try out and we'll rule them out one by one....
Once we find one that we can both agree on (or just stick with the request package we are using now) this issue can be closed

- [x] got | [npm link](https://www.npmjs.com/package/got) | **MARK TASK AS COMPLETE ONCE FINISHED TESTING AND CAN BE RULED OUT**
- [x] node-fetch | [npm link](https://www.npmjs.com/package/node-fetch) | **MARK TASK AS COMPLETE ONCE FINISHED TESTING AND CAN BE RULED OUT**
- [ ] bent | [npm link](https://www.npmjs.com/package/bent) | **MARK TASK AS COMPLETE ONCE FINISHED TESTING AND CAN BE RULED OUT**
- [ ] make-fetch-happen | [npm link](https://www.npmjs.com/package/make-fetch-happen) | **MARK TASK AS COMPLETE ONCE FINISHED TESTING AND CAN BE RULED OUT**
- [x] axios | [npm link](https://www.npmjs.com/package/axios) | **MARK TASK AS COMPLETE ONCE FINISHED TESTING AND CAN BE RULED OUT**
- [ ] unfetch | [npm link](https://www.npmjs.com/package/unfetch) | **MARK TASK AS COMPLETE ONCE FINISHED TESTING AND CAN BE RULED OUT**
- [x] superagent | [npm link](https://www.npmjs.com/package/superagent) | **MARK TASK AS COMPLETE ONCE FINISHED TESTING AND CAN BE RULED OUT**
- [ ] tiny-json-http | [npm link](https://www.npmjs.com/package/tiny-json-http) | **MARK TASK AS COMPLETE ONCE FINISHED TESTING AND CAN BE RULED OUT**
- [ ] needle | [npm link](https://www.npmjs.com/package/needle) | **MARK TASK AS COMPLETE ONCE FINISHED TESTING AND CAN BE RULED OUT**
- [ ] urllib | [npm link](https://www.npmjs.com/package/urllib) | **MARK TASK AS COMPLETE ONCE FINISHED TESTING AND CAN BE RULED OUT**
- [x] http node module method | **MARK TASK AS COMPLETE ONCE FINISHED TESTING AND CAN BE RULED OUT**

**Comment by j-koziel** [comment]
i've already ruled out node-fetch as it is quite slow

**Comment by j-koziel** [comment]
I'll try out got, bent, make-fetch-happen, axios and unfetch... you can test the rest when you get the time

**Comment by j-koziel** [comment]
testing to be done on the experimental branch

**Comment by JudeDavis1** [comment]
I believe I've used axios before, it's quite good.

**Comment by JudeDavis1** [comment]
I also did a from-scratch implementation somewhere but didn't commit it after I saw the 'request' library. I think I should I test the ready-made ones because my implementation, although was just about a little faster than request was very clunky to write.

**Comment by JudeDavis1** [comment]
*I-think-i-shouldn't

**Comment by j-koziel** [comment]
> I also did a from-scratch implementation somewhere but didn't commit it after I saw the 'request' library. I think I should I test the ready-made ones because my implementation, although was just about a little faster than request was very clunky to write.

we can test the bare bones node method as well and see how that compares... I'll add it to the list and you can try it out a bit more

**Comment by JudeDavis1** [comment]
It was using the socket.io module. I think we should just use an off-the-shelf library instead of writing using raw TCP sockets lol

**Comment by JudeDavis1** [comment]
btw, the package.json was moved somehow in the experimental branch

**Comment by JudeDavis1** [comment]
Any reason why?

**Comment by JudeDavis1** [comment]
There are a few bugs in package.json

**Comment by j-koziel** [comment]
> Any reason why?

since we made two separate applications for the front-end and backend I moved the node_modukes and package.json into the backend folder because when you use create-react-app it makes another package.json

**Comment by j-koziel** [comment]
> There are a few bugs in package.json

is it with the scripts?... might just have to change the commands slightly to mirror the changes

**Comment by JudeDavis1** [comment]
Fixed it

**Comment by JudeDavis1** [comment]
How does axios perform?

**Comment by j-koziel** [comment]
> How does axios perform?

i haven't tested it... if I have time I will try it today if not will try tomorrow

**Comment by JudeDavis1** [comment]
np

**Comment by j-koziel** [comment]
the got package seems to be quite slow so I'm ruling it out

**Comment by j-koziel** [comment]
woah.... i just tried out bent and it is extremely fast.... I think the response times are at least under half a second but I can't find out because for some reason morgan is not reporting anything
