### ISSUE TITLE
Bent broke :/

### ISSUE THREAD

**Issue by j-koziel** [cm-core-team/wol-api#14]
For some reason after I refactored getting the html into it's own function bent does not work anymore and I get a weird issue which completely breaks the server somehow.... 

![image](https://user-images.githubusercontent.com/68497216/201493677-d48e1ed7-bb99-484e-b0c3-3c29418d8fc6.png)

I have not yet tried doing it as I was doing it before but I am just putting this issue out there to see for your opinion @JudeDavis1 

TASKS:

- [x] Check if it still works the previous method -> Me :)

Of course can't forget the logs!

[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] starting `node ./build/server.js`
Server running on http://localhost:3000
StatusError: Not Found
    at ClientRequest.<anonymous> (H:\wol-api\src\backend\node_modules\bent\src\nodejs.js:133:23)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
    at TLSSocket.socketOnData (node:_http_client:534:22)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10) {
  statusCode: 404,
  json: [AsyncFunction (anonymous)],
  text: [Function (anonymous)],
  arrayBuffer: [Function (anonymous)],
  headers: {
    'content-type': 'text/html; charset=utf-8',
    'content-length': '7101',
    'x-frame-options': 'SAMEORIGIN',
    'x-content-type-options': 'nosniff',
    'x-xss-protection': '1;mode=block',
    'last-modified': 'Wed, 02 Nov 2022 04:07:08 GMT',
    etag: 'W/"bbc36ba44946a224148bb31b890bea59"',
    'content-encoding': 'gzip',
    'cache-control': 'public, max-age=21600, s-maxage=21600',
    expires: 'Sun, 13 Nov 2022 02:35:55 GMT',
    date: 'Sat, 12 Nov 2022 20:35:55 GMT',
    connection: 'close',
    vary: 'Accept-Encoding',
    'strict-transport-security': 'max-age=31536000'
  }
}
StatusError: Not Found
    at ClientRequest.<anonymous> (H:\wol-api\src\backend\node_modules\bent\src\nodejs.js:133:23)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
    at TLSSocket.socketOnData (node:_http_client:534:22)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10) {
  statusCode: 404,
  json: [AsyncFunction (anonymous)],
  text: [Function (anonymous)],
  arrayBuffer: [Function (anonymous)],
  headers: {
    'content-type': 'text/html; charset=utf-8',
    'content-length': '7101',
    'x-frame-options': 'SAMEORIGIN',
    'x-content-type-options': 'nosniff',
    'x-xss-protection': '1;mode=block',
    'last-modified': 'Wed, 02 Nov 2022 04:07:08 GMT',
    etag: 'W/"bbc36ba44946a224148bb31b890bea59"',
    'content-encoding': 'gzip',
    'cache-control': 'public, max-age=21600, s-maxage=21600',
    expires: 'Sun, 13 Nov 2022 02:35:55 GMT',
    date: 'Sat, 12 Nov 2022 20:35:55 GMT',
    connection: 'close',
    vary: 'Accept-Encoding',
    'strict-transport-security': 'max-age=31536000'
  }
}
StatusError: Not Found
    at ClientRequest.<anonymous> (H:\wol-api\src\backend\node_modules\bent\src\nodejs.js:133:23)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
    at TLSSocket.socketOnData (node:_http_client:534:22)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)

**Comment by j-koziel** [comment]
Doing it the normal way also does not seem to work

**Comment by JudeDavis1** [comment]
Hmmm. I'm not at my computer atm but It seems you are trying to access the backend at port 3000. The server.ts file clearly says it's listening on port 3001. 

Try going to port 3001.

**Comment by JudeDavis1** [comment]
Oh, oops, it appears I was on the dev branch

**Comment by JudeDavis1** [comment]
Ah. The wol.jw.org URL is incorrect, just tested it. Try with another one.

**Comment by JudeDavis1** [comment]
Tomorrow, if I get to go on my computer I'll try and fix it.

**Comment by j-koziel** [comment]
> Hmmm. I'm not at my computer atm but It seems you are trying to access the backend at port 3000. The server.ts file clearly says it's listening on port 3001. 
> 
> Try going to port 3001. 

I changed the port variable to 3000

**Comment by j-koziel** [comment]
> Ah. The wol.jw.org URL is incorrect, just tested it. Try with another one. 

I don't think it's that either... for me the wol.jw.org URL seems correct 🤔

**Comment by JudeDavis1** [comment]
![image](https://user-images.githubusercontent.com/51873868/201513708-3c6c9ecf-b3ec-4f7e-8c16-8927089d81ea.jpeg)

**Comment by j-koziel** [comment]
Could you send a screen shot of the url?

I'm trying both urls which we are accessing and they both work fine on my end 🤔

**Comment by j-koziel** [comment]
![image](https://user-images.githubusercontent.com/68497216/201514357-9ab72892-2e4d-4434-9c17-9dd8f11743cf.png)
This is what i get in postman testing the api

**Comment by JudeDavis1** [comment]
> Could you send a screen shot of the url?
> 
> I'm trying both urls which we are accessing and they both work fine on my end 🤔

Apologies, I made a mistake. Testing the URL on my computer works

**Comment by JudeDavis1** [comment]
I'll take a look at the headers

**Comment by j-koziel** [comment]
> I'll take a look at the headers

in postman you can turn off all the headers manually... after doing that it didn't work still

**Comment by JudeDavis1** [comment]
I dunno man. I've been editing, debugging, etc. for hours and I still can't find the problem

**Comment by j-koziel** [comment]
> I dunno man. I've been editing, debugging, etc. for hours and I still can't find the problem

yeah this seems to be strange... have you tried deleting node_modules and reinstalling... if you can't right now I can try that later which I'll probably do anyway. Maybe try also copying node_modules into the build folder?

**Comment by JudeDavis1** [comment]
However, I think Axios is worth a try. Bent requires extra code. In axios, you can do the json, html, string GETs in a one-liner. IMO it makes the code cleaner and there isn't a need to abstract the code into a getHTML function. I'll PR it.

**Comment by JudeDavis1** [comment]
I'll try, but it's not a bent problem. I isolated the EXACT code in a REPL, and it worked. It's not a library problem. It's something else

**Comment by j-koziel** [comment]
cool... i think I would still put it into a getHTML function because we would be repeating the axios code each time but whatever way suits you :)

**Comment by JudeDavis1** [comment]
I mean, you would still run getHTML(...) every time, wheras axios.get(...) or getString(...) would still be the same thing. The parsing is only a special case. I'll PR it and see what you think. BTW, the rm node_modules etc. didn't work

**Comment by j-koziel** [comment]
i also managed to get the Morgan Dev tool working again... it was a problem with my dotenv config 😭. The path option is really treacherous for that package 😂

**Comment by j-koziel** [comment]
> I mean, you would still run getHTML(...) every time, wheras axios.get(...) or getString(...) would still be the same thing. The parsing is only a special case. I'll PR it and see what you think. BTW, the rm node_modules etc. didn't work

cool

**Comment by j-koziel** [comment]
Ok so you were right this is not a bent issue.... i just tested axios and it also does not work.... I'm confused as to why it's receiving a 404 error

![image](https://user-images.githubusercontent.com/68497216/201624258-761d518f-07b1-46d3-8c89-f61837435616.png)

**Comment by j-koziel** [comment]
We have to start looking at what else could be causing this....

**Comment by j-koziel** [comment]
My first thought is that something must have messed up when we played around with the headers with the xss and helmet packages

**Comment by JudeDavis1** [comment]
It's possible, however I commented/uncommented the potentially problematic code, but no change. I didn't spend enough time on that. We'll take a further look this afternoon.

**Comment by j-koziel** [comment]
This probably sounds stupid because I dont know what im talking about but maybe the headers are cached somehow?

**Comment by j-koziel** [comment]
I SOLVED THE ISSUE

IT WAS A STUPID MISTAKE PRESENTED BY YOURS TRULY 😭😭🤣🤣💀💀

so... ✨BASICALLY ✨ it was actually a problem with how I was routing the endpoint. 

For some reason express did not like that I put another endpoint on the same route as the "getVerse" endpoint but somehow bent was sending back the error? Still confused but yeah... I'll commit into new_ok

**Comment by j-koziel** [comment]
@JudeDavis1 
sorry for the ping but im so happy 🤣😭

**Comment by JudeDavis1** [comment]
Commit that into experimental

**Comment by j-koziel** [comment]
I will

**Comment by JudeDavis1** [comment]
and we can delete the `new_ok` branch

**Comment by j-koziel** [comment]
should I merge or should I just commit into experimental?

**Comment by j-koziel** [comment]
ok so it's committed into experimental... Im going to close this issue now

**Comment by JudeDavis1** [comment]
Merge probably

**Comment by j-koziel** [comment]
ah well I already committed
