### ISSUE TITLE
api tokens?

### ISSUE THREAD

**Issue by j-koziel** [cm-core-team/wol-api#15]

**Comment by JudeDavis1** [comment]
👌

**Comment by j-koziel** [comment]
So I made the base model just now with some standard fields... if there are any other fields which you think people would need to provide to use this api

**Comment by JudeDavis1** [comment]
By `User`, do you mean API user (the engineer that is interfacing with it), or frontend user?

**Comment by j-koziel** [comment]
> By `User`, do you mean API user (the engineer that is using it), or frontend user?

API user

**Comment by JudeDavis1** [comment]
Right. I also think that this may be useful for mCart because it can suggest scriptures to do with ministry, angels guiding us, etc. if you know what I mean. 

If we can write an algo to index the scriptures, I can design a spicy ML algo to vectorize the scriptures and classify them based on topics. I can then display them on mCart as a 'featured' scripture or something.

**Comment by j-koziel** [comment]
> Right. I also think that this may be useful for mCart because it can suggest scriptures to do with ministry, angels guiding us, etc. if you know what I mean. 
> 
> If we can write an algo to index the scriptures, I can design a spicy ML algo to vectorize the scriptures and classify them based on topics. I can then display them on mCart as a 'featured' scripture or something. 

good idea... now please explain what you mean by index the scriptures... I'm sorry to have to do this 😭💀

**Comment by JudeDavis1** [comment]
No problem at all. By indexing, I mean to categorize, or order (index) by topic (or at least a few). Then with the ML algorithm, we can classify by topic/relevance

**Comment by j-koziel** [comment]
> No problem at all. By indexing, I mean to categorize, or order (index) by topic (or at least a few). Then with the ML algorithm, we can classify by topic/relevance 

Cool, thanks for explaining 👌

**Comment by JudeDavis1** [comment]
And I removed the `passwordConfirm` because that is to be done on the frontend, not the backend. I left a note next to the commit.

**Comment by j-koziel** [comment]
> No problem at all. By indexing, I mean to categorize, or order (index) by topic (or at least a few). Then with the ML algorithm, we can classify by topic/relevance

I know that mongodb actually has an indexing feature and you can use it to find documents quickly. Instead of looking through every single document to match a specific field mongo looks at the index and it only examines the necessary documents. This improves read performance for obvious reasons, but I wonder if the functionality extends further than read/write performance.

**Comment by JudeDavis1** [comment]
API tokens could be stores as part of a User model in mongoDB

**Comment by JudeDavis1** [comment]
stored*

**Comment by j-koziel** [comment]
Ok since I haven't really made any real progress for this in terms of commits and actual code im going to downgrade this to a discussion.
