### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by j-koziel** [cm-core-team/wol-api#171]
**Is your feature request related to a problem? Please describe.**
I was hoping that the URLs we're using to make requests to wol-api would only require the locale to change, however other parts of the url also change...

This is the url for english 
![image](https://user-images.githubusercontent.com/68497216/230627685-b5a614d4-0586-4ce4-b73c-d13d93db6acd.png)

The url for another language (this is polish as an example)
![image](https://user-images.githubusercontent.com/68497216/230627769-dd7e842e-654b-44f5-8e7d-7ffb1d70e368.png)

As you can see, other than the locale things like the "lp-e" and the "r1" tag have changed to "lp-p" and "r12"

**Describe the solution you'd like**
I'm guessing some kind of index which has all this other "metadata" which can be plugged into the req url

**Comment by JudeDavis1** [comment]
Not a bad idea. LGTM

**Comment by j-koziel** [comment]
for the future
