### ISSUE TITLE
Check for undefined when creating route

### ISSUE THREAD

**Issue by j-koziel** [cm-core-team/wol-api#3]
#2 @JudeDavis1 
Small thing but it should probably also check for undefined when passing in the route name, otherwise it just creates a route "undefined". I can work on this, so don't worry about it.

**Comment by JudeDavis1** [comment]
Oh right I knew I was missing something

**Comment by j-koziel** [comment]
Looks like you've fixed this now... thank you

**Comment by j-koziel** [comment]
btw I made some small changes to the route generator... It's to do with the route naming... If you check the latest commit I just made I put some comments in the route generator. TLDR - The route variable doesn't need to be named when creating it, can just be called "router". You change the name to something more specific when importing it into the app file

**Comment by JudeDavis1** [comment]
Ah right, I'll take a look now
