### ISSUE TITLE
When creating a new route, automatically add routeHandler function to controller folder

### ISSUE THREAD

**Issue by JudeDavis1** [cm-core-team/wol-api#4]
The route generator should add a handler in the controller folder. 

When creating a new route, should this happen regularly?

If so, I'll work on this.

**Comment by JudeDavis1** [comment]
Let me know if it should because I don't know much about the web engineering structure

**Comment by j-koziel** [comment]
> Let me know if it should because I don't know much about the web engineering structure

For most modern web apps there's an architecture called MVC (Model, View, Controller). The view is obviously what the client interacts with, which in our case I guess you could say is the routes that people would hit on the api (im not sure if that's completely accurate but it's just how I understand it). The controller is basically like the behind the scenes (middleware etc). Finally for the model.... well we don't really have any data models yet but we can probably expand on this in the future.

https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller

This article has pretty self explanatory diagrams which likely explain it much better :)

**Comment by JudeDavis1** [comment]
Ah yes MVC. I used that paradigm in some mobile applications. I guess the etymology of Model View Controller is a bit vague, so in our case I'd agree with you that the view may be the route endpoints (client). However, if we decided to write a frontend to display data then that would be the view

**Comment by JudeDavis1** [comment]
Yeah Wiki says 'some way of displaying information to the user' so I guess that the routes would be a means to display something like JSON or whatever like a RESTful API
