### ISSUE TITLE
Get all verses in a chapter

### ISSUE THREAD

**Issue by JudeDavis1** [cm-core-team/wol-api#99]
If we could add an endpoint to scrape all verses in a single chapter (all at once) and return it, that would speed up my transformer process.

**Comment by j-koziel** [comment]
this is going to have to be it for today...

**Comment by j-koziel** [comment]
I'm thinking to do this as an array of verses

It's easier that way as I can easily just map each verse into an array

**Comment by JudeDavis1** [comment]
The array is great, thanks a lot
